# -*- coding: utf-8 -*-
"""loading the data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KDwufFgudPlrc3lMQxcN1mBTDt2Bwt-9
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten,Conv2D,MaxPooling2D
import cv2

mnist=tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test)=mnist.load_data()

#gettting shape of data
print("Shape of training and testing dataset ")
print(x_train.shape)
print(x_test.shape)